name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: install python
        run: sudo apt-get install python3
      
      - name: install pre-commit   
        run: sudo pip install pre-commit
      
      - name: install truffle-hog   
        run: sudo curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin

      - name: create a precommit config file
        run: |
          cat <<EOF > .pre-commit-config.yaml
          repos:
          -   repo: https://github.com/psf/black
              rev: 22.10.0
              hooks:
              -   id: black
          -   repo: local
              hooks:
              - id: trufflehog
                name: TruffleHog
                description: Detect secrets in your data.
                entry: bash -c 'trufflehog git file://. --since-commit HEAD --no-verification --fail'
                language: system
                stages: ["commit", "push"]
          EOF 

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
