name: GitHub Actions Demo

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push, pull_request]

jobs:
  secret_checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install truffle-hog
        run: sudo curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin

      - name: Secret Scanning
        run: |
          trufflehog filesystem --only-verified --fail .

      - name: Commment if secrets are found
        if: failure()
        run: |
          echo ":: Secrects exposed, reverting to previous commit ::"
          echo ":: Do better next time ${{ vars.NAME }} ::"

      - name: No secrets found
        run: |
          echo ":: No secrects exposed ::"
