name: GitHub Actions Demo

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push, pull_request]

jobs:
  secret_checker:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: install truffle-hog   
        run: sudo curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin

      - name: Secret Scanning
        run: |
          echo $?
          trufflehog filesystem --only-verified --fail .
          echo $? 
      
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: |
            --only-verified
            --fail
      
      - name: Revert commit if lint fails
        if: failure()
        run: |
          echo ":: Secrects exposed, reverting to previous commit ::"
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git revert -m 1 HEAD
          git push origin main
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Revert commit if lint fails
        run: |
          echo ":: No secrects exposed ::"



      - name: List files in the repository
        run: |
          ls -la ${{ github.workspace }}